inhibit_all_warnings!
use_frameworks!

target 'OkLog-iOS' do
    platform :ios, '11.0'
    pod 'OkLog/Alamofire', :path => '../'

    target 'OkLog-Tests' do
        inherit! :search_paths
    end
end

target 'OkLog-macOS' do
    platform :osx, '10.13'
    pod 'OkLog/Alamofire', :path => '../'
end
